 ###############################################################################
#
# Erratum v1.02  ©2016-2019 Menz Agitat
# English language file - Fichier langue anglais (en)
#
 ###############################################################################

# uninstall
::msgcat::mcset en m0 "Deallocating %s resources..."
# loading
::msgcat::mcset en m1 "\00304\[%s - erreur\]\003 Configuration file could not be found at the specified location ( %s ). Script loading has been canceled."
::msgcat::mcset en m2 "%s v%s (©2016-2020 Menz Agitat) has been loaded."
# !erratum
::msgcat::mcset en m3 "\037Syntax\037 : \002%s\002 \00314<\003word/replacement\00314\[\003/word/replacement\00314\[\003/...\00314\]\]>\003 \00307|\003 Replaces each occurrence of \"word\" by \"replacement\" in a recently written line."
::msgcat::mcset en m4 "\037Error\037 : No match found."
::msgcat::mcset en m5 "\037Error\037 : Number of separators must be an odd number."
::msgcat::mcset en m6 "\037Error\037 : The word to replace can't be an empty string."
# antiflood
::msgcat::mcset en m7 "\00304:::\003 \00314Flood control has been triggered for all commands of %s: no more than %s %s every %s %s.\003"
::msgcat::mcset en m8 "request"
::msgcat::mcset en m9 "requests"
::msgcat::mcset en m10 "second"
::msgcat::mcset en m11 "seconds"
::msgcat::mcset en m12 "\00304:::\003 \00314Flood control has been triggered on all commands of %2\$s for %1\$s: no more than %3\$s %4\$s every %5\$s %6\$s.\003"
::msgcat::mcset en m13 "\00304:::\003 \00314Flood control has been triggered on the command \"%s\": no more than %s %s every %s %s.\003"
::msgcat::mcset en m14 "\00304:::\003 \00314Flood control has been triggered on the command \"%2\$s\" for %1\$s: no more than %3\$s %4\$s every %5\$s %6\$s.\003"
::msgcat::mcset en m15 "\00304:::\003 \00314Flood control is still active, please try again later.\003"
