 ###############################################################################
#
# Erratum v1.02  ©2016-2020 Menz Agitat
# French language file - Fichier langue français (fr)
#
 ###############################################################################

# désinstallation
::msgcat::mcset fr m0 "Désallocation des ressources de %s..."
# chargement
::msgcat::mcset fr m1 "\00304\[%s - erreur\]\003 Le fichier de configuration n'a pas été trouvé à l'emplacement indiqué ( %s ). Le chargement du script est annulé."
::msgcat::mcset fr m2 "%s v%s (©2016-2020 Menz Agitat) a été chargé."
# !erratum
::msgcat::mcset fr m3 "\037Syntaxe\037 : \002%s\002 \00314<\003mot/remplacement\00314\[\003/mot/remplacement\00314\[\003/...\00314\]\]>\003 \00307|\003 Remplace toutes les occurrences de \"mot\" par \"remplacement\" dans une ligne récemment écrite."
::msgcat::mcset fr m4 "\037Erreur\037 : Aucune correspondance n'a été trouvée."
::msgcat::mcset fr m5 "\037Erreur\037 : Les séparateurs doivent être en nombre impair."
::msgcat::mcset fr m6 "\037Erreur\037 : Le mot à remplacer ne peut être une chaîne de caractères vide."
# antiflood
::msgcat::mcset fr m7 "\00304:::\003 \00314Contrôle de flood activé pour toutes les commandes de %s : pas plus de %s %s toutes les %s %s.\003"
::msgcat::mcset fr m8 "requête"
::msgcat::mcset fr m9 "requêtes"
::msgcat::mcset fr m10 "seconde"
::msgcat::mcset fr m11 "secondes"
::msgcat::mcset fr m12 "\00304:::\003 \00314Contrôle de flood activé pour %s sur toutes les commandes de %s : pas plus de %s %s toutes les %s %s.\003"
::msgcat::mcset fr m13 "\00304:::\003 \00314Contrôle de flood activé pour la commande \"%s\" : pas plus de %s %s toutes les %s %s.\003"
::msgcat::mcset fr m14 "\00304:::\003 \00314Contrôle de flood activé pour %s sur la commande \"%s\" : pas plus de %s %s toutes les %s %s.\003"
::msgcat::mcset fr m15 "\00304:::\003 \00314Le contrôle de flood est toujours actif, merci de patienter.\003"
